#!/bin/sh
#
# Start Hiltop fan controller
#

start() {
	/usr/bin/hiltop-fan-controller &	
        echo $! > /tmp/hiltop-fan-controller.pid
}

stop() {
       if [ -f /tmp/hiltop-fan-controller.pid ]; then
           kill $(cat /tmp/hiltop-fan-controller.pid)
           rm /tmp/hiltop-fan-controller.pid
       fi
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
